version: "3"

services:
  app:
    build:
      args:
        - BASE_IMAGE=python:3.11.2-bullseye
        - PROJECT_NAME=app
        - USER_NAME=challenger
        - PYTHON_VERSION=3.11
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    volumes:
      - ../app:/home/challenger/Kakeibo
    ports:
      - 8888:8888
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    container_name: ${CONTAINER_NAME}
    hostname: ${HOST_NAME}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./db/postgres-init:/docker-entrypoint-initdb.d
    restart: always
    user: ${POSTGRES_USER}

  # DB確認用
  pgadmin4:
    image: dpage/pgadmin4
    #container_name: pgadmin4
    ports:
      - 8002:80
    volumes:
      - pgadmin4_volume:/var/lib/pgadmin
    env_file:
      - ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-db:
  pgadmin4_volume:
